doctoc ./src/1-basics.zh.md
doctoc ./src/2-structs-enums-lifetimes.zh.md
doctoc ./src/3-filesystem.zh.md
doctoc ./src/4-modules.zh.md
doctoc ./src/5-stdlib-containers.zh.md
doctoc ./src/6-error-handling.zh.md
doctoc ./src/7-shared-and-networking.zh.md
doctoc ./src/object-orientation.zh.md
doctoc ./src/nom-intro.zh.md
doctoc ./src/pain-points.zh.md